# Generated by Django 5.2.4 on 2025-07-27 08:46

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="로그인에 사용될 이메일 주소",
                        max_length=254,
                        unique=True,
                        verbose_name="이메일",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="이름")),
                ("last_name", models.CharField(max_length=30, verbose_name="성")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="프로필 이미지 (jpg, png, gif 지원)",
                        null=True,
                        upload_to="avatars/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                        verbose_name="프로필 이미지",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="간단한 자기소개",
                        max_length=500,
                        verbose_name="자기소개",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Seoul",
                        help_text="사용자의 시간대",
                        max_length=50,
                        verbose_name="시간대",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "라이트"),
                            ("dark", "다크"),
                            ("auto", "자동"),
                        ],
                        default="light",
                        max_length=10,
                        verbose_name="테마",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ko", "한국어"), ("en", "English")],
                        default="ko",
                        max_length=10,
                        verbose_name="언어",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="이메일 인증 여부"),
                ),
                (
                    "social_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google", "Google"),
                            ("kakao", "Kakao"),
                            ("naver", "Naver"),
                            ("github", "GitHub"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="소셜 로그인 제공자",
                    ),
                ),
                (
                    "social_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="소셜 로그인 ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="마지막 로그인 IP"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="인증 토큰"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="인증할 이메일"),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="사용 여부"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="만료 시간")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "이메일 인증 토큰",
                "verbose_name_plural": "이메일 인증 토큰들",
                "db_table": "email_verification_tokens",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="연락처 (선택사항)",
                        max_length=20,
                        verbose_name="전화번호",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="생년월일"),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="이메일로 알림 받기",
                        verbose_name="이메일 알림",
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="브라우저 푸시 알림 받기",
                        verbose_name="푸시 알림",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필들",
                "db_table": "user_profiles",
            },
        ),
    ]
